-- =====================================================================
-- Phase 4 - bulk load.  Run AFTER 00_server_setup.sql and schema.sql.
-- Order matters only for readability; there are no FK constraints (Phase 3).
-- =====================================================================
USE loan_portfolio;

-- Session tuning for bulk load. unique_checks stays ON deliberately:
-- it is what proves the Phase 2 primary keys actually hold.
SET SESSION foreign_key_checks = 0;
SET autocommit = 0;

-- application_train.csv  ->  application
LOAD DATA LOCAL INFILE 'C:/Users/acer/Documents/Data_Analytics_Project/Indian_loan_detection/data/raw/application_train.csv'
INTO TABLE `application`
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES
  (`SK_ID_CURR`, @v_TARGET, `NAME_CONTRACT_TYPE`, `CODE_GENDER`, `FLAG_OWN_CAR`, `FLAG_OWN_REALTY`, `CNT_CHILDREN`, `AMT_INCOME_TOTAL`, `AMT_CREDIT`, @v_AMT_ANNUITY, @v_AMT_GOODS_PRICE, @v_NAME_TYPE_SUITE, `NAME_INCOME_TYPE`, `NAME_EDUCATION_TYPE`, `NAME_FAMILY_STATUS`, `NAME_HOUSING_TYPE`, `REGION_POPULATION_RELATIVE`, `DAYS_BIRTH`, `DAYS_EMPLOYED`, `DAYS_REGISTRATION`, `DAYS_ID_PUBLISH`, @v_OWN_CAR_AGE, `FLAG_MOBIL`, `FLAG_EMP_PHONE`, `FLAG_WORK_PHONE`, `FLAG_CONT_MOBILE`, `FLAG_PHONE`, `FLAG_EMAIL`, @v_OCCUPATION_TYPE, @v_CNT_FAM_MEMBERS, `REGION_RATING_CLIENT`, `REGION_RATING_CLIENT_W_CITY`, `WEEKDAY_APPR_PROCESS_START`, `HOUR_APPR_PROCESS_START`, `REG_REGION_NOT_LIVE_REGION`, `REG_REGION_NOT_WORK_REGION`, `LIVE_REGION_NOT_WORK_REGION`, `REG_CITY_NOT_LIVE_CITY`, `REG_CITY_NOT_WORK_CITY`, `LIVE_CITY_NOT_WORK_CITY`, `ORGANIZATION_TYPE`, @v_EXT_SOURCE_1, @v_EXT_SOURCE_2, @v_EXT_SOURCE_3, @v_APARTMENTS_AVG, @v_BASEMENTAREA_AVG, @v_YEARS_BEGINEXPLUATATION_AVG, @v_YEARS_BUILD_AVG, @v_COMMONAREA_AVG, @v_ELEVATORS_AVG, @v_ENTRANCES_AVG, @v_FLOORSMAX_AVG, @v_FLOORSMIN_AVG, @v_LANDAREA_AVG, @v_LIVINGAPARTMENTS_AVG, @v_LIVINGAREA_AVG, @v_NONLIVINGAPARTMENTS_AVG, @v_NONLIVINGAREA_AVG, @v_APARTMENTS_MODE, @v_BASEMENTAREA_MODE, @v_YEARS_BEGINEXPLUATATION_MODE, @v_YEARS_BUILD_MODE, @v_COMMONAREA_MODE, @v_ELEVATORS_MODE, @v_ENTRANCES_MODE, @v_FLOORSMAX_MODE, @v_FLOORSMIN_MODE, @v_LANDAREA_MODE, @v_LIVINGAPARTMENTS_MODE, @v_LIVINGAREA_MODE, @v_NONLIVINGAPARTMENTS_MODE, @v_NONLIVINGAREA_MODE, @v_APARTMENTS_MEDI, @v_BASEMENTAREA_MEDI, @v_YEARS_BEGINEXPLUATATION_MEDI, @v_YEARS_BUILD_MEDI, @v_COMMONAREA_MEDI, @v_ELEVATORS_MEDI, @v_ENTRANCES_MEDI, @v_FLOORSMAX_MEDI, @v_FLOORSMIN_MEDI, @v_LANDAREA_MEDI, @v_LIVINGAPARTMENTS_MEDI, @v_LIVINGAREA_MEDI, @v_NONLIVINGAPARTMENTS_MEDI, @v_NONLIVINGAREA_MEDI, @v_FONDKAPREMONT_MODE, @v_HOUSETYPE_MODE, @v_TOTALAREA_MODE, @v_WALLSMATERIAL_MODE, @v_EMERGENCYSTATE_MODE, @v_OBS_30_CNT_SOCIAL_CIRCLE, @v_DEF_30_CNT_SOCIAL_CIRCLE, @v_OBS_60_CNT_SOCIAL_CIRCLE, @v_DEF_60_CNT_SOCIAL_CIRCLE, @v_DAYS_LAST_PHONE_CHANGE, `FLAG_DOCUMENT_2`, `FLAG_DOCUMENT_3`, `FLAG_DOCUMENT_4`, `FLAG_DOCUMENT_5`, `FLAG_DOCUMENT_6`, `FLAG_DOCUMENT_7`, `FLAG_DOCUMENT_8`, `FLAG_DOCUMENT_9`, `FLAG_DOCUMENT_10`, `FLAG_DOCUMENT_11`, `FLAG_DOCUMENT_12`, `FLAG_DOCUMENT_13`, `FLAG_DOCUMENT_14`, `FLAG_DOCUMENT_15`, `FLAG_DOCUMENT_16`, `FLAG_DOCUMENT_17`, `FLAG_DOCUMENT_18`, `FLAG_DOCUMENT_19`, `FLAG_DOCUMENT_20`, `FLAG_DOCUMENT_21`, @v_AMT_REQ_CREDIT_BUREAU_HOUR, @v_AMT_REQ_CREDIT_BUREAU_DAY, @v_AMT_REQ_CREDIT_BUREAU_WEEK, @v_AMT_REQ_CREDIT_BUREAU_MON, @v_AMT_REQ_CREDIT_BUREAU_QRT, @v_AMT_REQ_CREDIT_BUREAU_YEAR)
SET
  `SOURCE` = 'train',
  `TARGET` = NULLIF(@v_TARGET, ''),
  `AMT_ANNUITY` = NULLIF(@v_AMT_ANNUITY, ''),
  `AMT_GOODS_PRICE` = NULLIF(@v_AMT_GOODS_PRICE, ''),
  `NAME_TYPE_SUITE` = NULLIF(@v_NAME_TYPE_SUITE, ''),
  `OWN_CAR_AGE` = NULLIF(@v_OWN_CAR_AGE, ''),
  `OCCUPATION_TYPE` = NULLIF(@v_OCCUPATION_TYPE, ''),
  `CNT_FAM_MEMBERS` = NULLIF(@v_CNT_FAM_MEMBERS, ''),
  `EXT_SOURCE_1` = NULLIF(@v_EXT_SOURCE_1, ''),
  `EXT_SOURCE_2` = NULLIF(@v_EXT_SOURCE_2, ''),
  `EXT_SOURCE_3` = NULLIF(@v_EXT_SOURCE_3, ''),
  `APARTMENTS_AVG` = NULLIF(@v_APARTMENTS_AVG, ''),
  `BASEMENTAREA_AVG` = NULLIF(@v_BASEMENTAREA_AVG, ''),
  `YEARS_BEGINEXPLUATATION_AVG` = NULLIF(@v_YEARS_BEGINEXPLUATATION_AVG, ''),
  `YEARS_BUILD_AVG` = NULLIF(@v_YEARS_BUILD_AVG, ''),
  `COMMONAREA_AVG` = NULLIF(@v_COMMONAREA_AVG, ''),
  `ELEVATORS_AVG` = NULLIF(@v_ELEVATORS_AVG, ''),
  `ENTRANCES_AVG` = NULLIF(@v_ENTRANCES_AVG, ''),
  `FLOORSMAX_AVG` = NULLIF(@v_FLOORSMAX_AVG, ''),
  `FLOORSMIN_AVG` = NULLIF(@v_FLOORSMIN_AVG, ''),
  `LANDAREA_AVG` = NULLIF(@v_LANDAREA_AVG, ''),
  `LIVINGAPARTMENTS_AVG` = NULLIF(@v_LIVINGAPARTMENTS_AVG, ''),
  `LIVINGAREA_AVG` = NULLIF(@v_LIVINGAREA_AVG, ''),
  `NONLIVINGAPARTMENTS_AVG` = NULLIF(@v_NONLIVINGAPARTMENTS_AVG, ''),
  `NONLIVINGAREA_AVG` = NULLIF(@v_NONLIVINGAREA_AVG, ''),
  `APARTMENTS_MODE` = NULLIF(@v_APARTMENTS_MODE, ''),
  `BASEMENTAREA_MODE` = NULLIF(@v_BASEMENTAREA_MODE, ''),
  `YEARS_BEGINEXPLUATATION_MODE` = NULLIF(@v_YEARS_BEGINEXPLUATATION_MODE, ''),
  `YEARS_BUILD_MODE` = NULLIF(@v_YEARS_BUILD_MODE, ''),
  `COMMONAREA_MODE` = NULLIF(@v_COMMONAREA_MODE, ''),
  `ELEVATORS_MODE` = NULLIF(@v_ELEVATORS_MODE, ''),
  `ENTRANCES_MODE` = NULLIF(@v_ENTRANCES_MODE, ''),
  `FLOORSMAX_MODE` = NULLIF(@v_FLOORSMAX_MODE, ''),
  `FLOORSMIN_MODE` = NULLIF(@v_FLOORSMIN_MODE, ''),
  `LANDAREA_MODE` = NULLIF(@v_LANDAREA_MODE, ''),
  `LIVINGAPARTMENTS_MODE` = NULLIF(@v_LIVINGAPARTMENTS_MODE, ''),
  `LIVINGAREA_MODE` = NULLIF(@v_LIVINGAREA_MODE, ''),
  `NONLIVINGAPARTMENTS_MODE` = NULLIF(@v_NONLIVINGAPARTMENTS_MODE, ''),
  `NONLIVINGAREA_MODE` = NULLIF(@v_NONLIVINGAREA_MODE, ''),
  `APARTMENTS_MEDI` = NULLIF(@v_APARTMENTS_MEDI, ''),
  `BASEMENTAREA_MEDI` = NULLIF(@v_BASEMENTAREA_MEDI, ''),
  `YEARS_BEGINEXPLUATATION_MEDI` = NULLIF(@v_YEARS_BEGINEXPLUATATION_MEDI, ''),
  `YEARS_BUILD_MEDI` = NULLIF(@v_YEARS_BUILD_MEDI, ''),
  `COMMONAREA_MEDI` = NULLIF(@v_COMMONAREA_MEDI, ''),
  `ELEVATORS_MEDI` = NULLIF(@v_ELEVATORS_MEDI, ''),
  `ENTRANCES_MEDI` = NULLIF(@v_ENTRANCES_MEDI, ''),
  `FLOORSMAX_MEDI` = NULLIF(@v_FLOORSMAX_MEDI, ''),
  `FLOORSMIN_MEDI` = NULLIF(@v_FLOORSMIN_MEDI, ''),
  `LANDAREA_MEDI` = NULLIF(@v_LANDAREA_MEDI, ''),
  `LIVINGAPARTMENTS_MEDI` = NULLIF(@v_LIVINGAPARTMENTS_MEDI, ''),
  `LIVINGAREA_MEDI` = NULLIF(@v_LIVINGAREA_MEDI, ''),
  `NONLIVINGAPARTMENTS_MEDI` = NULLIF(@v_NONLIVINGAPARTMENTS_MEDI, ''),
  `NONLIVINGAREA_MEDI` = NULLIF(@v_NONLIVINGAREA_MEDI, ''),
  `FONDKAPREMONT_MODE` = NULLIF(@v_FONDKAPREMONT_MODE, ''),
  `HOUSETYPE_MODE` = NULLIF(@v_HOUSETYPE_MODE, ''),
  `TOTALAREA_MODE` = NULLIF(@v_TOTALAREA_MODE, ''),
  `WALLSMATERIAL_MODE` = NULLIF(@v_WALLSMATERIAL_MODE, ''),
  `EMERGENCYSTATE_MODE` = NULLIF(@v_EMERGENCYSTATE_MODE, ''),
  `OBS_30_CNT_SOCIAL_CIRCLE` = NULLIF(@v_OBS_30_CNT_SOCIAL_CIRCLE, ''),
  `DEF_30_CNT_SOCIAL_CIRCLE` = NULLIF(@v_DEF_30_CNT_SOCIAL_CIRCLE, ''),
  `OBS_60_CNT_SOCIAL_CIRCLE` = NULLIF(@v_OBS_60_CNT_SOCIAL_CIRCLE, ''),
  `DEF_60_CNT_SOCIAL_CIRCLE` = NULLIF(@v_DEF_60_CNT_SOCIAL_CIRCLE, ''),
  `DAYS_LAST_PHONE_CHANGE` = NULLIF(@v_DAYS_LAST_PHONE_CHANGE, ''),
  `AMT_REQ_CREDIT_BUREAU_HOUR` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_HOUR, ''),
  `AMT_REQ_CREDIT_BUREAU_DAY` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_DAY, ''),
  `AMT_REQ_CREDIT_BUREAU_WEEK` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_WEEK, ''),
  `AMT_REQ_CREDIT_BUREAU_MON` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_MON, ''),
  `AMT_REQ_CREDIT_BUREAU_QRT` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_QRT, ''),
  `AMT_REQ_CREDIT_BUREAU_YEAR` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_YEAR, '');
SHOW WARNINGS;

COMMIT;

-- application_test.csv  ->  application
LOAD DATA LOCAL INFILE 'C:/Users/acer/Documents/Data_Analytics_Project/Indian_loan_detection/data/raw/application_test.csv'
INTO TABLE `application`
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES
  (`SK_ID_CURR`, `NAME_CONTRACT_TYPE`, `CODE_GENDER`, `FLAG_OWN_CAR`, `FLAG_OWN_REALTY`, `CNT_CHILDREN`, `AMT_INCOME_TOTAL`, `AMT_CREDIT`, @v_AMT_ANNUITY, @v_AMT_GOODS_PRICE, @v_NAME_TYPE_SUITE, `NAME_INCOME_TYPE`, `NAME_EDUCATION_TYPE`, `NAME_FAMILY_STATUS`, `NAME_HOUSING_TYPE`, `REGION_POPULATION_RELATIVE`, `DAYS_BIRTH`, `DAYS_EMPLOYED`, `DAYS_REGISTRATION`, `DAYS_ID_PUBLISH`, @v_OWN_CAR_AGE, `FLAG_MOBIL`, `FLAG_EMP_PHONE`, `FLAG_WORK_PHONE`, `FLAG_CONT_MOBILE`, `FLAG_PHONE`, `FLAG_EMAIL`, @v_OCCUPATION_TYPE, @v_CNT_FAM_MEMBERS, `REGION_RATING_CLIENT`, `REGION_RATING_CLIENT_W_CITY`, `WEEKDAY_APPR_PROCESS_START`, `HOUR_APPR_PROCESS_START`, `REG_REGION_NOT_LIVE_REGION`, `REG_REGION_NOT_WORK_REGION`, `LIVE_REGION_NOT_WORK_REGION`, `REG_CITY_NOT_LIVE_CITY`, `REG_CITY_NOT_WORK_CITY`, `LIVE_CITY_NOT_WORK_CITY`, `ORGANIZATION_TYPE`, @v_EXT_SOURCE_1, @v_EXT_SOURCE_2, @v_EXT_SOURCE_3, @v_APARTMENTS_AVG, @v_BASEMENTAREA_AVG, @v_YEARS_BEGINEXPLUATATION_AVG, @v_YEARS_BUILD_AVG, @v_COMMONAREA_AVG, @v_ELEVATORS_AVG, @v_ENTRANCES_AVG, @v_FLOORSMAX_AVG, @v_FLOORSMIN_AVG, @v_LANDAREA_AVG, @v_LIVINGAPARTMENTS_AVG, @v_LIVINGAREA_AVG, @v_NONLIVINGAPARTMENTS_AVG, @v_NONLIVINGAREA_AVG, @v_APARTMENTS_MODE, @v_BASEMENTAREA_MODE, @v_YEARS_BEGINEXPLUATATION_MODE, @v_YEARS_BUILD_MODE, @v_COMMONAREA_MODE, @v_ELEVATORS_MODE, @v_ENTRANCES_MODE, @v_FLOORSMAX_MODE, @v_FLOORSMIN_MODE, @v_LANDAREA_MODE, @v_LIVINGAPARTMENTS_MODE, @v_LIVINGAREA_MODE, @v_NONLIVINGAPARTMENTS_MODE, @v_NONLIVINGAREA_MODE, @v_APARTMENTS_MEDI, @v_BASEMENTAREA_MEDI, @v_YEARS_BEGINEXPLUATATION_MEDI, @v_YEARS_BUILD_MEDI, @v_COMMONAREA_MEDI, @v_ELEVATORS_MEDI, @v_ENTRANCES_MEDI, @v_FLOORSMAX_MEDI, @v_FLOORSMIN_MEDI, @v_LANDAREA_MEDI, @v_LIVINGAPARTMENTS_MEDI, @v_LIVINGAREA_MEDI, @v_NONLIVINGAPARTMENTS_MEDI, @v_NONLIVINGAREA_MEDI, @v_FONDKAPREMONT_MODE, @v_HOUSETYPE_MODE, @v_TOTALAREA_MODE, @v_WALLSMATERIAL_MODE, @v_EMERGENCYSTATE_MODE, @v_OBS_30_CNT_SOCIAL_CIRCLE, @v_DEF_30_CNT_SOCIAL_CIRCLE, @v_OBS_60_CNT_SOCIAL_CIRCLE, @v_DEF_60_CNT_SOCIAL_CIRCLE, @v_DAYS_LAST_PHONE_CHANGE, `FLAG_DOCUMENT_2`, `FLAG_DOCUMENT_3`, `FLAG_DOCUMENT_4`, `FLAG_DOCUMENT_5`, `FLAG_DOCUMENT_6`, `FLAG_DOCUMENT_7`, `FLAG_DOCUMENT_8`, `FLAG_DOCUMENT_9`, `FLAG_DOCUMENT_10`, `FLAG_DOCUMENT_11`, `FLAG_DOCUMENT_12`, `FLAG_DOCUMENT_13`, `FLAG_DOCUMENT_14`, `FLAG_DOCUMENT_15`, `FLAG_DOCUMENT_16`, `FLAG_DOCUMENT_17`, `FLAG_DOCUMENT_18`, `FLAG_DOCUMENT_19`, `FLAG_DOCUMENT_20`, `FLAG_DOCUMENT_21`, @v_AMT_REQ_CREDIT_BUREAU_HOUR, @v_AMT_REQ_CREDIT_BUREAU_DAY, @v_AMT_REQ_CREDIT_BUREAU_WEEK, @v_AMT_REQ_CREDIT_BUREAU_MON, @v_AMT_REQ_CREDIT_BUREAU_QRT, @v_AMT_REQ_CREDIT_BUREAU_YEAR)
SET
  `SOURCE` = 'test',
  `AMT_ANNUITY` = NULLIF(@v_AMT_ANNUITY, ''),
  `AMT_GOODS_PRICE` = NULLIF(@v_AMT_GOODS_PRICE, ''),
  `NAME_TYPE_SUITE` = NULLIF(@v_NAME_TYPE_SUITE, ''),
  `OWN_CAR_AGE` = NULLIF(@v_OWN_CAR_AGE, ''),
  `OCCUPATION_TYPE` = NULLIF(@v_OCCUPATION_TYPE, ''),
  `CNT_FAM_MEMBERS` = NULLIF(@v_CNT_FAM_MEMBERS, ''),
  `EXT_SOURCE_1` = NULLIF(@v_EXT_SOURCE_1, ''),
  `EXT_SOURCE_2` = NULLIF(@v_EXT_SOURCE_2, ''),
  `EXT_SOURCE_3` = NULLIF(@v_EXT_SOURCE_3, ''),
  `APARTMENTS_AVG` = NULLIF(@v_APARTMENTS_AVG, ''),
  `BASEMENTAREA_AVG` = NULLIF(@v_BASEMENTAREA_AVG, ''),
  `YEARS_BEGINEXPLUATATION_AVG` = NULLIF(@v_YEARS_BEGINEXPLUATATION_AVG, ''),
  `YEARS_BUILD_AVG` = NULLIF(@v_YEARS_BUILD_AVG, ''),
  `COMMONAREA_AVG` = NULLIF(@v_COMMONAREA_AVG, ''),
  `ELEVATORS_AVG` = NULLIF(@v_ELEVATORS_AVG, ''),
  `ENTRANCES_AVG` = NULLIF(@v_ENTRANCES_AVG, ''),
  `FLOORSMAX_AVG` = NULLIF(@v_FLOORSMAX_AVG, ''),
  `FLOORSMIN_AVG` = NULLIF(@v_FLOORSMIN_AVG, ''),
  `LANDAREA_AVG` = NULLIF(@v_LANDAREA_AVG, ''),
  `LIVINGAPARTMENTS_AVG` = NULLIF(@v_LIVINGAPARTMENTS_AVG, ''),
  `LIVINGAREA_AVG` = NULLIF(@v_LIVINGAREA_AVG, ''),
  `NONLIVINGAPARTMENTS_AVG` = NULLIF(@v_NONLIVINGAPARTMENTS_AVG, ''),
  `NONLIVINGAREA_AVG` = NULLIF(@v_NONLIVINGAREA_AVG, ''),
  `APARTMENTS_MODE` = NULLIF(@v_APARTMENTS_MODE, ''),
  `BASEMENTAREA_MODE` = NULLIF(@v_BASEMENTAREA_MODE, ''),
  `YEARS_BEGINEXPLUATATION_MODE` = NULLIF(@v_YEARS_BEGINEXPLUATATION_MODE, ''),
  `YEARS_BUILD_MODE` = NULLIF(@v_YEARS_BUILD_MODE, ''),
  `COMMONAREA_MODE` = NULLIF(@v_COMMONAREA_MODE, ''),
  `ELEVATORS_MODE` = NULLIF(@v_ELEVATORS_MODE, ''),
  `ENTRANCES_MODE` = NULLIF(@v_ENTRANCES_MODE, ''),
  `FLOORSMAX_MODE` = NULLIF(@v_FLOORSMAX_MODE, ''),
  `FLOORSMIN_MODE` = NULLIF(@v_FLOORSMIN_MODE, ''),
  `LANDAREA_MODE` = NULLIF(@v_LANDAREA_MODE, ''),
  `LIVINGAPARTMENTS_MODE` = NULLIF(@v_LIVINGAPARTMENTS_MODE, ''),
  `LIVINGAREA_MODE` = NULLIF(@v_LIVINGAREA_MODE, ''),
  `NONLIVINGAPARTMENTS_MODE` = NULLIF(@v_NONLIVINGAPARTMENTS_MODE, ''),
  `NONLIVINGAREA_MODE` = NULLIF(@v_NONLIVINGAREA_MODE, ''),
  `APARTMENTS_MEDI` = NULLIF(@v_APARTMENTS_MEDI, ''),
  `BASEMENTAREA_MEDI` = NULLIF(@v_BASEMENTAREA_MEDI, ''),
  `YEARS_BEGINEXPLUATATION_MEDI` = NULLIF(@v_YEARS_BEGINEXPLUATATION_MEDI, ''),
  `YEARS_BUILD_MEDI` = NULLIF(@v_YEARS_BUILD_MEDI, ''),
  `COMMONAREA_MEDI` = NULLIF(@v_COMMONAREA_MEDI, ''),
  `ELEVATORS_MEDI` = NULLIF(@v_ELEVATORS_MEDI, ''),
  `ENTRANCES_MEDI` = NULLIF(@v_ENTRANCES_MEDI, ''),
  `FLOORSMAX_MEDI` = NULLIF(@v_FLOORSMAX_MEDI, ''),
  `FLOORSMIN_MEDI` = NULLIF(@v_FLOORSMIN_MEDI, ''),
  `LANDAREA_MEDI` = NULLIF(@v_LANDAREA_MEDI, ''),
  `LIVINGAPARTMENTS_MEDI` = NULLIF(@v_LIVINGAPARTMENTS_MEDI, ''),
  `LIVINGAREA_MEDI` = NULLIF(@v_LIVINGAREA_MEDI, ''),
  `NONLIVINGAPARTMENTS_MEDI` = NULLIF(@v_NONLIVINGAPARTMENTS_MEDI, ''),
  `NONLIVINGAREA_MEDI` = NULLIF(@v_NONLIVINGAREA_MEDI, ''),
  `FONDKAPREMONT_MODE` = NULLIF(@v_FONDKAPREMONT_MODE, ''),
  `HOUSETYPE_MODE` = NULLIF(@v_HOUSETYPE_MODE, ''),
  `TOTALAREA_MODE` = NULLIF(@v_TOTALAREA_MODE, ''),
  `WALLSMATERIAL_MODE` = NULLIF(@v_WALLSMATERIAL_MODE, ''),
  `EMERGENCYSTATE_MODE` = NULLIF(@v_EMERGENCYSTATE_MODE, ''),
  `OBS_30_CNT_SOCIAL_CIRCLE` = NULLIF(@v_OBS_30_CNT_SOCIAL_CIRCLE, ''),
  `DEF_30_CNT_SOCIAL_CIRCLE` = NULLIF(@v_DEF_30_CNT_SOCIAL_CIRCLE, ''),
  `OBS_60_CNT_SOCIAL_CIRCLE` = NULLIF(@v_OBS_60_CNT_SOCIAL_CIRCLE, ''),
  `DEF_60_CNT_SOCIAL_CIRCLE` = NULLIF(@v_DEF_60_CNT_SOCIAL_CIRCLE, ''),
  `DAYS_LAST_PHONE_CHANGE` = NULLIF(@v_DAYS_LAST_PHONE_CHANGE, ''),
  `AMT_REQ_CREDIT_BUREAU_HOUR` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_HOUR, ''),
  `AMT_REQ_CREDIT_BUREAU_DAY` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_DAY, ''),
  `AMT_REQ_CREDIT_BUREAU_WEEK` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_WEEK, ''),
  `AMT_REQ_CREDIT_BUREAU_MON` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_MON, ''),
  `AMT_REQ_CREDIT_BUREAU_QRT` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_QRT, ''),
  `AMT_REQ_CREDIT_BUREAU_YEAR` = NULLIF(@v_AMT_REQ_CREDIT_BUREAU_YEAR, '');
SHOW WARNINGS;

COMMIT;

-- bureau.csv  ->  bureau
LOAD DATA LOCAL INFILE 'C:/Users/acer/Documents/Data_Analytics_Project/Indian_loan_detection/data/raw/bureau.csv'
INTO TABLE `bureau`
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES
  (`SK_ID_CURR`, `SK_ID_BUREAU`, `CREDIT_ACTIVE`, `CREDIT_CURRENCY`, `DAYS_CREDIT`, `CREDIT_DAY_OVERDUE`, @v_DAYS_CREDIT_ENDDATE, @v_DAYS_ENDDATE_FACT, @v_AMT_CREDIT_MAX_OVERDUE, `CNT_CREDIT_PROLONG`, @v_AMT_CREDIT_SUM, @v_AMT_CREDIT_SUM_DEBT, @v_AMT_CREDIT_SUM_LIMIT, `AMT_CREDIT_SUM_OVERDUE`, `CREDIT_TYPE`, `DAYS_CREDIT_UPDATE`, @v_AMT_ANNUITY)
SET
  `DAYS_CREDIT_ENDDATE` = NULLIF(@v_DAYS_CREDIT_ENDDATE, ''),
  `DAYS_ENDDATE_FACT` = NULLIF(@v_DAYS_ENDDATE_FACT, ''),
  `AMT_CREDIT_MAX_OVERDUE` = NULLIF(@v_AMT_CREDIT_MAX_OVERDUE, ''),
  `AMT_CREDIT_SUM` = NULLIF(@v_AMT_CREDIT_SUM, ''),
  `AMT_CREDIT_SUM_DEBT` = NULLIF(@v_AMT_CREDIT_SUM_DEBT, ''),
  `AMT_CREDIT_SUM_LIMIT` = NULLIF(@v_AMT_CREDIT_SUM_LIMIT, ''),
  `AMT_ANNUITY` = NULLIF(@v_AMT_ANNUITY, '');
SHOW WARNINGS;

COMMIT;

-- bureau_balance.csv  ->  bureau_balance
LOAD DATA LOCAL INFILE 'C:/Users/acer/Documents/Data_Analytics_Project/Indian_loan_detection/data/raw/bureau_balance.csv'
INTO TABLE `bureau_balance`
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES
  (`SK_ID_BUREAU`, `MONTHS_BALANCE`, `STATUS`);
SHOW WARNINGS;

COMMIT;

-- previous_application.csv  ->  previous_application
LOAD DATA LOCAL INFILE 'C:/Users/acer/Documents/Data_Analytics_Project/Indian_loan_detection/data/raw/previous_application.csv'
INTO TABLE `previous_application`
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES
  (`SK_ID_PREV`, `SK_ID_CURR`, `NAME_CONTRACT_TYPE`, @v_AMT_ANNUITY, `AMT_APPLICATION`, @v_AMT_CREDIT, @v_AMT_DOWN_PAYMENT, @v_AMT_GOODS_PRICE, `WEEKDAY_APPR_PROCESS_START`, `HOUR_APPR_PROCESS_START`, `FLAG_LAST_APPL_PER_CONTRACT`, `NFLAG_LAST_APPL_IN_DAY`, @v_RATE_DOWN_PAYMENT, @v_RATE_INTEREST_PRIMARY, @v_RATE_INTEREST_PRIVILEGED, `NAME_CASH_LOAN_PURPOSE`, `NAME_CONTRACT_STATUS`, `DAYS_DECISION`, `NAME_PAYMENT_TYPE`, `CODE_REJECT_REASON`, @v_NAME_TYPE_SUITE, `NAME_CLIENT_TYPE`, `NAME_GOODS_CATEGORY`, `NAME_PORTFOLIO`, `NAME_PRODUCT_TYPE`, `CHANNEL_TYPE`, `SELLERPLACE_AREA`, `NAME_SELLER_INDUSTRY`, @v_CNT_PAYMENT, `NAME_YIELD_GROUP`, @v_PRODUCT_COMBINATION, @v_DAYS_FIRST_DRAWING, @v_DAYS_FIRST_DUE, @v_DAYS_LAST_DUE_1ST_VERSION, @v_DAYS_LAST_DUE, @v_DAYS_TERMINATION, @v_NFLAG_INSURED_ON_APPROVAL)
SET
  `AMT_ANNUITY` = NULLIF(@v_AMT_ANNUITY, ''),
  `AMT_CREDIT` = NULLIF(@v_AMT_CREDIT, ''),
  `AMT_DOWN_PAYMENT` = NULLIF(@v_AMT_DOWN_PAYMENT, ''),
  `AMT_GOODS_PRICE` = NULLIF(@v_AMT_GOODS_PRICE, ''),
  `RATE_DOWN_PAYMENT` = NULLIF(@v_RATE_DOWN_PAYMENT, ''),
  `RATE_INTEREST_PRIMARY` = NULLIF(@v_RATE_INTEREST_PRIMARY, ''),
  `RATE_INTEREST_PRIVILEGED` = NULLIF(@v_RATE_INTEREST_PRIVILEGED, ''),
  `NAME_TYPE_SUITE` = NULLIF(@v_NAME_TYPE_SUITE, ''),
  `CNT_PAYMENT` = NULLIF(@v_CNT_PAYMENT, ''),
  `PRODUCT_COMBINATION` = NULLIF(@v_PRODUCT_COMBINATION, ''),
  `DAYS_FIRST_DRAWING` = NULLIF(@v_DAYS_FIRST_DRAWING, ''),
  `DAYS_FIRST_DUE` = NULLIF(@v_DAYS_FIRST_DUE, ''),
  `DAYS_LAST_DUE_1ST_VERSION` = NULLIF(@v_DAYS_LAST_DUE_1ST_VERSION, ''),
  `DAYS_LAST_DUE` = NULLIF(@v_DAYS_LAST_DUE, ''),
  `DAYS_TERMINATION` = NULLIF(@v_DAYS_TERMINATION, ''),
  `NFLAG_INSURED_ON_APPROVAL` = NULLIF(@v_NFLAG_INSURED_ON_APPROVAL, '');
SHOW WARNINGS;

COMMIT;

-- POS_CASH_balance.csv  ->  pos_cash_balance
LOAD DATA LOCAL INFILE 'C:/Users/acer/Documents/Data_Analytics_Project/Indian_loan_detection/data/raw/POS_CASH_balance.csv'
INTO TABLE `pos_cash_balance`
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES
  (`SK_ID_PREV`, `SK_ID_CURR`, `MONTHS_BALANCE`, @v_CNT_INSTALMENT, @v_CNT_INSTALMENT_FUTURE, `NAME_CONTRACT_STATUS`, `SK_DPD`, `SK_DPD_DEF`)
SET
  `CNT_INSTALMENT` = NULLIF(@v_CNT_INSTALMENT, ''),
  `CNT_INSTALMENT_FUTURE` = NULLIF(@v_CNT_INSTALMENT_FUTURE, '');
SHOW WARNINGS;

COMMIT;

-- credit_card_balance.csv  ->  credit_card_balance
LOAD DATA LOCAL INFILE 'C:/Users/acer/Documents/Data_Analytics_Project/Indian_loan_detection/data/raw/credit_card_balance.csv'
INTO TABLE `credit_card_balance`
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES
  (`SK_ID_PREV`, `SK_ID_CURR`, `MONTHS_BALANCE`, `AMT_BALANCE`, `AMT_CREDIT_LIMIT_ACTUAL`, @v_AMT_DRAWINGS_ATM_CURRENT, `AMT_DRAWINGS_CURRENT`, @v_AMT_DRAWINGS_OTHER_CURRENT, @v_AMT_DRAWINGS_POS_CURRENT, @v_AMT_INST_MIN_REGULARITY, @v_AMT_PAYMENT_CURRENT, `AMT_PAYMENT_TOTAL_CURRENT`, `AMT_RECEIVABLE_PRINCIPAL`, `AMT_RECIVABLE`, `AMT_TOTAL_RECEIVABLE`, @v_CNT_DRAWINGS_ATM_CURRENT, `CNT_DRAWINGS_CURRENT`, @v_CNT_DRAWINGS_OTHER_CURRENT, @v_CNT_DRAWINGS_POS_CURRENT, @v_CNT_INSTALMENT_MATURE_CUM, `NAME_CONTRACT_STATUS`, `SK_DPD`, `SK_DPD_DEF`)
SET
  `AMT_DRAWINGS_ATM_CURRENT` = NULLIF(@v_AMT_DRAWINGS_ATM_CURRENT, ''),
  `AMT_DRAWINGS_OTHER_CURRENT` = NULLIF(@v_AMT_DRAWINGS_OTHER_CURRENT, ''),
  `AMT_DRAWINGS_POS_CURRENT` = NULLIF(@v_AMT_DRAWINGS_POS_CURRENT, ''),
  `AMT_INST_MIN_REGULARITY` = NULLIF(@v_AMT_INST_MIN_REGULARITY, ''),
  `AMT_PAYMENT_CURRENT` = NULLIF(@v_AMT_PAYMENT_CURRENT, ''),
  `CNT_DRAWINGS_ATM_CURRENT` = NULLIF(@v_CNT_DRAWINGS_ATM_CURRENT, ''),
  `CNT_DRAWINGS_OTHER_CURRENT` = NULLIF(@v_CNT_DRAWINGS_OTHER_CURRENT, ''),
  `CNT_DRAWINGS_POS_CURRENT` = NULLIF(@v_CNT_DRAWINGS_POS_CURRENT, ''),
  `CNT_INSTALMENT_MATURE_CUM` = NULLIF(@v_CNT_INSTALMENT_MATURE_CUM, '');
SHOW WARNINGS;

COMMIT;

-- installments_payments.csv  ->  installments_payments
LOAD DATA LOCAL INFILE 'C:/Users/acer/Documents/Data_Analytics_Project/Indian_loan_detection/data/raw/installments_payments.csv'
INTO TABLE `installments_payments`
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES
  (`SK_ID_PREV`, `SK_ID_CURR`, `NUM_INSTALMENT_VERSION`, `NUM_INSTALMENT_NUMBER`, `DAYS_INSTALMENT`, @v_DAYS_ENTRY_PAYMENT, `AMT_INSTALMENT`, @v_AMT_PAYMENT)
SET
  `DAYS_ENTRY_PAYMENT` = NULLIF(@v_DAYS_ENTRY_PAYMENT, ''),
  `AMT_PAYMENT` = NULLIF(@v_AMT_PAYMENT, '');
SHOW WARNINGS;

COMMIT;


SET SESSION foreign_key_checks = 1;
SET autocommit = 1;
